/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-02-13 09:08:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import swVo.WishlistListVo;
import swVo.WishlistVo;
import java.text.DecimalFormat;
import esVo.UserInfoVo;
import esVo.LanguageVo;
import java.util.ArrayList;
import myDao.*;
import myVo.*;
import esDao.*;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("esDao");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("myVo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("myDao");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("swVo.WishlistListVo");
    _jspx_imports_classes.add("swVo.WishlistVo");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("esVo.LanguageVo");
    _jspx_imports_classes.add("esVo.UserInfoVo");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
	
	//카테고리 목록을 받음12345
	ArrayList<RoomCategoryVo> roomcate = (ArrayList<RoomCategoryVo>)request.getAttribute("list1"); // roomcate는 
	int paramCate = (Integer)request.getAttribute("cateIdx");   // cate= 국립공원
	ArrayList<RepresentRoomListVo> roomList = (ArrayList<RepresentRoomListVo>)request.getAttribute("roomVo"); 
	ArrayList<WishlistListVo> listWish = (ArrayList<WishlistListVo>) request.getAttribute("listWish");
    RealWishlistDao wDao = new RealWishlistDao();
	
	Main2Dao dao = new Main2Dao();
	// 광화문 위도경도
	double currentLatitude = 126.96033;
	double currentLongitude = 37.264842;
	LoginDao LoginDao = new LoginDao();
	LanguageDao langDao = new LanguageDao();
	ArrayList<LanguageVo> listLanguageVo = langDao.getLanguage();
	int userIdx = 0;
	UserInfoVo userList = null;
	int howManyAlarm = 0;
	if(request.getSession().getAttribute("userIdx") != null) {
		try{
			userIdx = (Integer)request.getSession().getAttribute("userIdx"); //--> 로그인창 만들면 이걸로 적용하기	
			userList = LoginDao.getUserInfoBy(userIdx);
			howManyAlarm = (Integer)LoginDao.getCountAlarm(userIdx);
		} catch (NullPointerException e){
			e.printStackTrace();
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>여행은 살아보는거야-에어비앤비</title>\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/reset.css\">\r\n");
      out.write("   <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/main2.css\"/>\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>   \r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick.css\"/>\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"css/slick-theme.css\"/>   \r\n");
      out.write("	<script src = \"js/jquery-3.7.1.min.js\"></script>\r\n");
      out.write("	<script src = \"js/jquery-ui.min.js\"></script>\r\n");
      out.write("   <script src = \"js/main2.js\"></script>\r\n");
      out.write("	<!-- 날짜 -->\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\" integrity=\"sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\" integrity=\"sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css\" integrity=\"sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  	<!--슬릭  -->\r\n");
      out.write("   <script type=\"text/javascript\" src=\"http://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>   \r\n");
      out.write("</head>	\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id = mini_box>\r\n");
      out.write("지도 표시하기\r\n");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 16px; width: 16px;\"><path d=\"M31.25 3.75a2.29 2.29 0 0 0-1.01-1.44A2.29 2.29 0 0 0 28.5 2L21 3.67l-10-2L2.5 3.56A2.29 2.29 0 0 0 .7 5.8v21.95a2.28 2.28 0 0 0 1.06 1.94A2.29 2.29 0 0 0 3.5 30L11 28.33l10 2 8.49-1.89a2.29 2.29 0 0 0 1.8-2.24V4.25a2.3 2.3 0 0 0-.06-.5zM12.5 25.98l-1.51-.3L9.5 26H9.5V4.66l1.51-.33 1.49.3v21.34zm10 1.36-1.51.33-1.49-.3V6.02l1.51.3L22.5 6h.01v21.34z\"></path></svg>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"currency_language_background\"></div>\r\n");
      out.write("				<div id=\"currency_language_\">\r\n");
      out.write("					<button class=\"close_div\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg></button>\r\n");
      out.write("					<div id=\"currency_\">\r\n");
      out.write("						<div id=\"currency_top\">\r\n");
      out.write("							<button class=\"currency_button fl\">언어와 지역</button>\r\n");
      out.write("							<button class=\"language_button fl\">통화</button>\r\n");
      out.write("						</div><!--currency_top-->\r\n");
      out.write("						<div id=\"currency_center\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<h2>추천 언어 및 지역</h2>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li class=\"fl\">\r\n");
      out.write("										<div>English</div>\r\n");
      out.write("										<div>United States</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li class=\"fl\">\r\n");
      out.write("										<div>English</div>\r\n");
      out.write("										<div>United States</div>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<h3 style=\"font-size: 22px; font-weight: 600;\">언어와 지역을 선택하세요</h3>\r\n");
      out.write("						");

                        		for( int i = 0; i <= 90; i++ ){
  									if(i % 5 == 0)
  										out.println("<ul>");
                        
      out.write("\r\n");
      out.write("                         	  <li class=\"fl\">\r\n");
      out.write("                            	  <div>");
      out.print(listLanguageVo.get(i).getLanguage() );
      out.write("</div>\r\n");
      out.write("                              	<div>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</div>\r\n");
      out.write("                         	  </li>\r\n");
      out.write("                        ");

                        		if(i % 5 == 4)
                        			out.println("</ul>");
                        		}
                        
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div><!--currency_center-->\r\n");
      out.write("					</div><!--currency_-->\r\n");
      out.write("					<div id=\"language_\"></div><!--language_-->\r\n");
      out.write("				</div><!--currency_language_-->\r\n");
      out.write("		<div id=\"header\">\r\n");
      out.write("			<div id=\"header_left\" class=\"fl\">\r\n");
      out.write("				<a href=\"Main2\"><img src=\"images/logo.png\" class=\"fr\"/></a>\r\n");
      out.write("			</div><!--header_left-- <!--airbnbë¡ê³ -->\r\n");
      out.write("			<div id=\"center\" class=\"fl\">\r\n");
      out.write("				<div class= \"btns\">\r\n");
      out.write("		          <button class =\"btn1\">\r\n");
      out.write("		            <div>어디든지</div>\r\n");
      out.write("		          </button>\r\n");
      out.write("		          <button class =\"btn2\">\r\n");
      out.write("		                <div>언제든 일주일</div>\r\n");
      out.write("		          </button>\r\n");
      out.write("		          <button class =\"btn3\">\r\n");
      out.write("		              <div>게스트 추가</div>\r\n");
      out.write("		              <div><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;fill:none;height:12px;width:12px;stroke:currentColor;stroke-width:5.333333333333333;overflow:visible\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"><path fill=\"none\" d=\"M13 24a11 11 0 1 0 0-22 11 11 0 0 0 0 22zm8-3 9 9\"></path></svg></div>\r\n");
      out.write("		          </button> \r\n");
      out.write("		        </div>\r\n");
      out.write("			</div><!--header_center--> \r\n");
      out.write("			<div id=\"center2\" class=\"fl\" style=\"display:none;\">\r\n");
      out.write("		         <div class=\"btn4\">숙소</div>\r\n");
      out.write("		         <div class=\"btn5\">체험</div>\r\n");
      out.write("		         <div class=\"btn6\">온라인 체험</div>\r\n");
      out.write("   			</div>\r\n");
      out.write("			<div id=\"header_right\" class=\"fl\">\r\n");
      out.write("				<div id=\"areaair\" class=\"fl\">\r\n");
      out.write("					<a href=\"doairbnb.jsp\"><strong>당신의 공간을 에어비앤비하세요</strong></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"globe\" class=\"fl\">\r\n");
      out.write("					<img src=\"images/globe.png\"/>\r\n");
      out.write("				</div><!--globe-->\r\n");
      out.write("				<div id=\"profile\" class=\"fl\">\r\n");
      out.write("					<img src=\"images/list.png\" style=\"margin: 21px 0 0 0px;\"/>\r\n");
      out.write("					");
 		if(userIdx == 0) { 
      out.write("\r\n");
      out.write("								<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("						");
  } else { 
      out.write("\r\n");
      out.write("								");
 if(userList.getUser_image() != null) { 
      out.write("\r\n");
      out.write("								<img src=\"");
      out.print(userList.getUser_image() );
      out.write("\"/>\r\n");
      out.write("								");
 } else { 
      out.write("\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 30px; width: 40px; fill: currentcolor; margin: -30px 0 0 41px;\"><path d=\"M16 .7C7.56.7.7 7.56.7 16S7.56 31.3 16 31.3 31.3 24.44 31.3 16 24.44.7 16 .7zm0 28c-4.02 0-7.6-1.88-9.93-4.81a12.43 12.43 0 0 1 6.45-4.4A6.5 6.5 0 0 1 9.5 14a6.5 6.5 0 0 1 13 0 6.51 6.51 0 0 1-3.02 5.5 12.42 12.42 0 0 1 6.45 4.4A12.67 12.67 0 0 1 16 28.7z\"></path></svg>\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("								<div id=\"notice\">");
      out.print(howManyAlarm );
      out.write("</div>\r\n");
      out.write("						");
    } 
      out.write("\r\n");
      out.write("				</div><!--profile-->\r\n");
      out.write("				<div style =\"clear : both;\"></div>\r\n");
      out.write("				<div class=\"profile_list\">\r\n");
      out.write("					");
 if(userIdx > 0) { 
      out.write(" \r\n");
      out.write("					<div class=\"profile_list_top\">\r\n");
      out.write("						<form action=\"SesController\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"메시지\"/>\r\n");
      out.write("							<input type=\"hidden\" name=\"thisUserIdx\" value=\"0\"/>\r\n");
      out.write("							<input type=\"hidden\" name=\"command\" value=\"message\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"notification.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"알림\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"trip.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"여행\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"wishlist.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"위시리스트\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div><!--profile_list_top-->\r\n");
      out.write("					<div class=\"profile_list_center\">\r\n");
      out.write("						<form action=\"doairbnb.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"당신의 공간을 에어비앤비하세요\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form action=\"account.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"계정\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div><!--profile_list_center-->\r\n");
      out.write("					<div class=\"profile_list_bottom\">\r\n");
      out.write("						<form action=\"timeline.jsp\" method=\"post\">\r\n");
      out.write("							<input type=\"submit\" value=\"타임라인\"/>\r\n");
      out.write("						</form>\r\n");
      out.write("						<div class=\"Logout\">로그아웃</div>\r\n");
      out.write("					</div><!--profile_list_bottom-->\r\n");
      out.write("				 	");
 } else{ 
      out.write("\r\n");
      out.write("					<div class=\"profile_list_diff\">\r\n");
      out.write("						<div>로그인</div>\r\n");
      out.write("						<div>회원가입</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				</div><!--profile_list-->\r\n");
      out.write("			</div><!--header_right-->\r\n");
      out.write("			<div style =\"clear : both;\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 회원가입창 -->\r\n");
      out.write("   <div id=\"joinmember_outer\"></div>\r\n");
      out.write("      <div id=\"joinmember\">\r\n");
      out.write("      \r\n");
      out.write("         <div class=\"jm_header\">\r\n");
      out.write("            <button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("            <h2>로그인 또는 회원 가입</h2>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"jm_section\">\r\n");
      out.write("            <h2>에어비엔비에 오신것을 환영합니다</h2>\r\n");
      out.write("         \r\n");
      out.write("            <form id=\"jm_form\" action=\"lmyController\" method=\"post\">\r\n");
      out.write("               <div>\r\n");
      out.write("                  <label for=\"jm_form\" id=\"code\"></label> \r\n");
      out.write("                  <select name=\"jm_code\" class=\"jm_seclect_box\">\r\n");
      out.write("                     <option value=\"korean\">선호하는 언어</option>\r\n");
      out.write("                     ");
 for(int i = 0; i <= 90; i++) { 
      out.write("\r\n");
      out.write("                  	 		<option>");
      out.print(listLanguageVo.get(i).getLocation() );
      out.write("</option>\r\n");
      out.write("                  	 ");
 } 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("	               </div>\r\n");
      out.write("	               \r\n");
      out.write("	               <input type=\"text\" class=\"jm_phnum\" placeholder=\"전화번호\" name=\"phone_num\" required/>\r\n");
      out.write("	           	   <input type=\"password\" class=\"password\" placeholder=\"비밀번호\" name=\"pw\" required/>\r\n");
      out.write("	               <span>전화나 문자로 전화번호를 확인하겠습니다. 일반 문자 메시지 요금 및 데이터 요금이 부과됩니다.</span>\r\n");
      out.write("	         	   <input type=\"hidden\" name=\"url\" value=\"Main2\"/>\r\n");
      out.write("	         	   <input type=\"hidden\" name=\"command\" value=\"login\"/>\r\n");
      out.write("	               <input type=\"submit\" class=\"jm_submit\" value=\"로그인\"><br/>\r\n");
      out.write("               <div class=\"join_user\" style=\"padding-top: 16px;\">회원 가입</div>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"join_user\">\r\n");
      out.write("      		<button>\r\n");
      out.write("               <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"\r\n");
      out.write("                  aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"\r\n");
      out.write("                  style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible; margin: 0 auto;\">\r\n");
      out.write("                  <path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("            </button>\r\n");
      out.write("      		<form method=\"post\" class=\"join_user_form\" action=\"lmyController\">\r\n");
      out.write("      			이름 : <input type=\"text\" placeholder=\"Ex) 김철수\" name=\"user_id\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 : <input type=\"password\" name=\"pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			비밀번호 확인 : <input type=\"password\" class=\"check_pw\" required/> <br/><br/><br/>\r\n");
      out.write("      			휴대폰 번호 : <input type=\"number\" name=\"phone_num\" placeholder=\"010xxxx1234\" required/> <br/><br/><br/>\r\n");
      out.write("      			거주지 : <input type=\"text\" name=\"user_regidence\" required/> <br/><br/><br/>\r\n");
      out.write("      			생년월일 : <input type=\"text\" name=\"birthday\" placeholder=\"2000/12/12\"required/> <br/><br/><br/>\r\n");
      out.write("      			이메일 : <input type=\"email\" name=\"email\" placeholder=\"asd123@naver.com\" required/> <br/><br/><br/><br/>\r\n");
      out.write("      			<input type=\"hidden\" name=\"command\" value=\"join\"/>\r\n");
      out.write("      			<input type=\"submit\" style=\"width: 500px; background-color: rgb(255,56,92); border-radius: 10px; color: white; border: none;}\"/>\r\n");
      out.write("      		</form>\r\n");
      out.write("      </div>\r\n");
      out.write("<!--회원가입창 끝  -->\r\n");
      out.write("<!-- header2 -->\r\n");
      out.write("<div id=\"header2\" style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("<!-- ----------세부창 -->\r\n");
      out.write("	<div id=\"head_pop1\" style=\"display:none;\"><!--오랜지  -->\r\n");
      out.write("		<div class=\"pop_content1\"><!-- 하늘색 -->\r\n");
      out.write("			<div class=\"pop_content1-1\">최근 검색 내역</div>\r\n");
      out.write("			<div class=\"pop_content1-2\">\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"pop_content1-3\">\r\n");
      out.write("					<div class= \"pop_content1-4\">\r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 22px; width: 22px; fill: currentcolor;\"><path d=\"M16 .33a15.67 15.67 0 1 1 0 31.34A15.67 15.67 0 0 1 16 .33zm0 2a13.67 13.67 0 1 0 0 27.34 13.67 13.67 0 0 0 0-27.34zm1 3v10.1l8.74 5.04-1 1.73L15 16.58V5.33z\"></path></svg>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class= \"pop_content1-5\">\r\n");
      out.write("						<span>제주도 · 숙소</span><br>\r\n");
      out.write("						언제든일주일\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"pop_content1-3\">\r\n");
      out.write("					<div class= \"pop_content1-4\">\r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 22px; width: 22px; fill: currentcolor;\"><path d=\"M16 .33a15.67 15.67 0 1 1 0 31.34A15.67 15.67 0 0 1 16 .33zm0 2a13.67 13.67 0 1 0 0 27.34 13.67 13.67 0 0 0 0-27.34zm1 3v10.1l8.74 5.04-1 1.73L15 16.58V5.33z\"></path></svg>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class= \"pop_content1-5\">\r\n");
      out.write("						<span>용산구 · 숙소</span><br>\r\n");
      out.write("						 12월 14일~16일\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div><!-- 왼쪽끝 -->\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"pop_content2\" >\r\n");
      out.write("			<div class=\"pop_content2-1\">지역으로 검색하기</div>\r\n");
      out.write("			<div class=\"pop_content2-2\"> <!-- 지역그리드 -->\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/pictures/f9ec8a23-ed44-420b-83e5-10ff1f071a13.jpg\"/>\r\n");
      out.write("					<span>유연한 검색</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/im/pictures/d77de9f5-5318-4571-88c7-e97d2355d20a.jpg\"/>\r\n");
      out.write("					<span>아시아</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/pictures/f9ec8a23-ed44-420b-83e5-10ff1f071a13.jpg\"/>\r\n");
      out.write("					<span>오세아니아</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/im/pictures/4e762891-75a3-4fe1-b73a-cd7e673ba915.jpg\"/>\r\n");
      out.write("					<span>아메리카</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/pictures/f9ec8a23-ed44-420b-83e5-10ff1f071a13.jpg\"/>\r\n");
      out.write("					<span>아프리카</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"pop_content2-3\">\r\n");
      out.write("					<img src=\"https://a0.muscache.com/im/pictures/7b5cf816-6c16-49f8-99e5-cbc4adfd97e2.jpg\"/>\r\n");
      out.write("					<span>유럽</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 세부차1번끝  -->\r\n");
      out.write("<div id=\"head_pop2\" style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"hpop_content1\">\r\n");
      out.write("		<div class=\"hpop_content1-1\">\r\n");
      out.write("			<div>날짜 지정</div>\r\n");
      out.write("			<div>월 단위</div>\r\n");
      out.write("			<div>유연한 일정</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"hpop_content2\">\r\n");
      out.write("		<div class=\"hpop_content2-1\">\r\n");
      out.write("		 	<div id=\"dp1\" name=\"dp1\" class=\"datepicker\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"hpop_content2-2\">\r\n");
      out.write("			<div id=\"dp2\" name=\"dp2\" class=\"datepicker2\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	 \r\n");
      out.write("	<div class=\"hpop_content3\">\r\n");
      out.write("		<div class=\"hpop_content3-1\">정확한날짜</div>\r\n");
      out.write("		<div class=\"hpop_content3-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 2.66667; overflow: visible;\"><path fill=\"none\" d=\"M16 4v16m-8-8h16M8 26h16\"></path></svg>1일</div>\r\n");
      out.write("		<div class=\"hpop_content3-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 2.66667; overflow: visible;\"><path fill=\"none\" d=\"M16 4v16m-8-8h16M8 26h16\"></path></svg> 2일</div>\r\n");
      out.write("		<div class=\"hpop_content3-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 2.66667; overflow: visible;\"><path fill=\"none\" d=\"M16 4v16m-8-8h16M8 26h16\"></path></svg> 3일</div>\r\n");
      out.write("		<div class=\"hpop_content3-2\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 2.66667; overflow: visible;\"><path fill=\"none\" d=\"M16 4v16m-8-8h16M8 26h16\"></path></svg> 7일</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 세부창2끝 -->\r\n");
      out.write("<div id=\"head_pop3\" style=\"display:none;\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"hpop_content1\">\r\n");
      out.write("		<div class=\"hpop_content1-1\">\r\n");
      out.write("			<div>날짜 지정</div>\r\n");
      out.write("			<div>월 단위</div>\r\n");
      out.write("			<div>유연한 일정</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"hpop_content4\">\r\n");
      out.write("		<span>숙박기간을 선택해주세요</span>\r\n");
      out.write("		<div class=\"hpop_content4-1\">\r\n");
      out.write("			<div>주말</div>\r\n");
      out.write("			<div>일주일</div>\r\n");
      out.write("			<div>한 달</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div  class=\"hpop_content5\">\r\n");
      out.write("		<span>여행날짜를 선택하세요</span>\r\n");
      out.write("		<div class=\"hpop_content5-1\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span>12월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span> 1월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span> 2월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span> 3월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span> 4월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/pictures/cf82c9bc-520a-4486-9be4-1f0927972381.jpg\" />\r\n");
      out.write("				<span> 5월</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"hpop_content5-2\">\r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 5.33333; overflow: visible;\"><path fill=\"none\" d=\"m12 4 11.3 11.3a1 1 0 0 1 0 1.4L12 28\"></path></svg>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 세부창3끝 -->\r\n");
      out.write("<div id=\"head_pop4\" style=\"display:none;\" >\r\n");
      out.write("	<div class=\"hpop_content6\"><!--오렌지  -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<span class=\"hop_content6-1\">성인</span>\r\n");
      out.write("				<span class=\"hop_content6-2\">13세 이상</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button class= \"hop4_btn1\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m.75 6.75h10.5v-1.5h-10.5z\"></path></svg></button> \r\n");
      out.write("				<input type=\"text\" class=\"hop4_input\" value=\"0\"/>\r\n");
      out.write("				<button class=\"hop4_btn2\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m6.75.75v4.5h4.5v1.5h-4.5v4.5h-1.5v-4.5h-4.5v-1.5h4.5v-4.5z\"></path></svg></button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"hpop_content6\"><!--오렌지  -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<span class=\"hop_content6-1\">어린이</span>\r\n");
      out.write("			<span class=\"hop_content6-2\">2~12세</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button class= \"hop4_btn1\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m.75 6.75h10.5v-1.5h-10.5z\"></path></svg></button> \r\n");
      out.write("				<input type=\"text\" class=\"hop4_input\" value=\"0\"/>\r\n");
      out.write("				<button class=\"hop4_btn2\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m6.75.75v4.5h4.5v1.5h-4.5v4.5h-1.5v-4.5h-4.5v-1.5h4.5v-4.5z\"></path></svg></button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"hpop_content6\"><!--오렌지  -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<span class=\"hop_content6-1\">유아</span>\r\n");
      out.write("				<span class=\"hop_content6-2\">2세 미만</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button class= \"hop4_btn1\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m.75 6.75h10.5v-1.5h-10.5z\"></path></svg></button> \r\n");
      out.write("				<input type=\"text\" class=\"hop4_input\" value=\"0\"/>\r\n");
      out.write("				<button class=\"hop4_btn2\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m6.75.75v4.5h4.5v1.5h-4.5v4.5h-1.5v-4.5h-4.5v-1.5h4.5v-4.5z\"></path></svg></button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<div class=\"hpop_content6\" style=\"border-bottom:none;\"><!--오렌지  -->\r\n");
      out.write("			<div>\r\n");
      out.write("				<span class=\"hop_content6-1\">반려동물</span>\r\n");
      out.write("				<span class=\"hop_content6-3\">보조동물을 동반하시나요?</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<button class= \"hop4_btn1\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m.75 6.75h10.5v-1.5h-10.5z\"></path></svg></button> \r\n");
      out.write("				<input type=\"text\" class=\"hop4_input\" value=\"0\"/>\r\n");
      out.write("				<button class=\"hop4_btn2\"><svg viewBox=\"0 0 12 12\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; height: 12px; width: 12px; fill: currentcolor;margin-left: 9.2px;\"><path d=\"m6.75.75v4.5h4.5v1.5h-4.5v4.5h-1.5v-4.5h-4.5v-1.5h4.5v-4.5z\"></path></svg></button>\r\n");
      out.write("			</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--세부창4끝  -->\r\n");
      out.write("<!--세부창 끝  -->	\r\n");
      out.write("\r\n");
      out.write("	<div id=\"header_inner\">\r\n");
      out.write("		<div class=\"head_content1\">\r\n");
      out.write("			<span>여행지</span>\r\n");
      out.write("			<input type=\"text\" id=\"head_input\" name=\"email\" placeholder=\"여행지 검색\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"head_content2\">\r\n");
      out.write("			<span>체크인</span>\r\n");
      out.write("			<span>날짜추가</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"head_content3\">\r\n");
      out.write("			<span>체크아웃</span>\r\n");
      out.write("			<span>날짜추가</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"head_content4\">\r\n");
      out.write("			<span>여행자</span>\r\n");
      out.write("			<span>게스트 추가</span>\r\n");
      out.write("			<div class=\"head_svg\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 4; overflow: visible;\"><path fill=\"none\" d=\"M13 24a11 11 0 1 0 0-22 11 11 0 0 0 0 22zm8-3 9 9\"></path></svg>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- header2끝  -->\r\n");
      out.write("<div id =\"section\">\r\n");
      out.write("	<div id=\"menu\">\r\n");
      out.write("	 <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: inline;fill: none;height: 12px;width: 12px; stroke: currentcolor;stroke-width: 5.33333;overflow: visible;position: absolute;left: 62px;top: 29px;\"><path fill=\"none\" d=\"M20 28 8.7 16.7a1 1 0 0 1 0-1.4L20 4\"></path></svg>\r\n");
      out.write("		<div id =\"cate\">\r\n");
      out.write("			<!--  -->\r\n");
      out.write("			");
 for( RoomCategoryVo vo : roomcate ){ 
      out.write("\r\n");
      out.write("				<div class=\"w hover\">\r\n");
      out.write("					<span>\r\n");
      out.write("						<img src=\"");
      out.print( vo.getCategory_icon());
      out.write("\"/>\r\n");
      out.write("						<div><span>");
      out.print(vo.getCategory_name() );
      out.write("</span></div>\r\n");
      out.write("						<div style=\"display:none;\">");
      out.print(vo.getRoom_category_idx() );
      out.write("</div>\r\n");
      out.write("<!-- 					<div class=\"bar\" style=\"width:62.5625px; height:2px;background-color:black; visibility:hidden; \"></div> -->\r\n");
      out.write("					</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div><!-- 카테끝 -->\r\n");
      out.write("		 <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; cursor : pointer; fill: none; height: 12px; width: 12px; stroke: currentcolor; stroke-width: 5.33333; overflow: visible;position: absolute;top: 28.5px;right: 160px;\"><path fill=\"none\" d=\"m12 4 11.3 11.3a1 1 0 0 1 0 1.4L12 28\"></path></svg>\r\n");
      out.write("		<div id=\"menu_btn\">\r\n");
      out.write("			<button>\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" style=\"display:block;fill:none;height:16px;width:16px;stroke:currentColor;stroke-width:3;overflow:visible\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\"><path fill=\"none\" d=\"M7 16H3m26 0H15M29 6h-4m-8 0H3m26 20h-4M7 16a4 4 0 1 0 8 0 4 4 0 0 0-8 0zM17 6a4 4 0 1 0 8 0 4 4 0 0 0-8 0zm0 20a4 4 0 1 0 8 0 4 4 0 0 0-8 0zm0 0H3\"></path></svg>\r\n");
      out.write("				<a>필터</a>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div><!-- 메뉴끝 -->\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 내용 -->\r\n");
      out.write("<div id=\"content_outer\">\r\n");
      out.write("	<div id=\"content\">\r\n");
      out.write("<!-- 		<a>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"https://a0.muscache.com/im/pictures/34822e87-1915-4f1e-9ae0-a5b0cccbce1e.jpg?im_w=1200\"/>\r\n");
      out.write("				<button><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: rgba(0, 0, 0, 0.5); height: 24px; width: 22.7px; stroke:white; stroke-width: 2; overflow: visible;\"><path d=\"M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z\"></path></svg></button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"ps\">\r\n");
      out.write("				<div>토스카나 | 수영장과 레스토랑이 있는 농장 체험 숙박</div>\r\n");
      out.write("				<span>★  5.0</span>\r\n");
      out.write("				<div>치악산국립공원에서 60km</div>\r\n");
      out.write("				<div>12월 3일~8일</div>\r\n");
      out.write("				<div><b>₩294,455</b> /박</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</a> -->\r\n");
      out.write("		");
 for(RepresentRoomListVo r : roomList){ 
      out.write("\r\n");
      out.write("		");
 double roomLatitude = r.getLatitude(); 
		   double roomLongitude = r.getLongitude();
		
      out.write("\r\n");
      out.write("		");

		double distance = dao.checkDistance(currentLatitude, currentLongitude, roomLatitude, roomLongitude);
		if(paramCate == 8 || paramCate == 2) {
			distance = dao.checkDistance1(currentLatitude, currentLongitude, roomLatitude, roomLongitude); 
		}
		
      out.write("\r\n");
      out.write("			<a>	\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"");
      out.print(r.getImg1() );
      out.write("\"/>\r\n");
      out.write("					<svg class =\"heart_empty\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: rgba(0, 0, 0, 0.5); height: 24px; width: 22.7px; stroke:white; stroke-width: 2; overflow: visible;\"><path d=\"M16 28c7-4.73 14-10 14-17a6.98 6.98 0 0 0-7-7c-1.8 0-3.58.68-4.95 2.05L16 8.1l-2.05-2.05a6.98 6.98 0 0 0-9.9 0A6.98 6.98 0 0 0 2 11c0 7 7 12.27 14 17z\"></path></svg>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"ps\">\r\n");
      out.write("					<div>");
      out.print( r.getRoomName());
      out.write("</div>\r\n");
      out.write("					<span>★");
      out.print( r.getRoomScore());
      out.write("</span>\r\n");
      out.write("					<div>광화문에서 ");
      out.print(distance );
      out.write("km</div>\r\n");
      out.write("					<div>12월 3일~8일</div>\r\n");
      out.write("					<div><b>₩");
      out.print( new DecimalFormat("###,###").format(r.getRoomPrice()) );
      out.write("</b> /박</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"room_idx\" style=\"display:none;\">");
      out.print(r.getRoomIdx());
      out.write("</div>\r\n");
      out.write("			</a>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 위시팝업 -->\r\n");
      out.write("<input type=\"hidden\" id=\"heart_val\"/>\r\n");
      out.write("<div id=\"wish_outer\"></div>\r\n");
      out.write("<div id=\"wish\" >\r\n");
      out.write("	<div class=\"wish_header\">\r\n");
      out.write("		<button>\r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;position:absolute;top: 20px;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("		</button>\r\n");
      out.write("		<span>위시리스트에 담기</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"wish_inner1\">\r\n");
      out.write("		");
if(listWish != null){ 
      out.write("\r\n");
      out.write("		");
 for(WishlistListVo vo : listWish) { 
      out.write(" \r\n");
      out.write("		<div class=\"wish_content_outer\">\r\n");
      out.write("			<div class=\"wish_content1\">\r\n");
      out.write("				<img src=\"");
      out.print(vo.getImg());
      out.write("\"/>\r\n");
      out.write("				<span class=\"wish_sp1\">");
      out.print(vo.getBiglistName() );
      out.write("</span><br>\r\n");
      out.write("				<span class=\"wish_sp2\">");
      out.print(vo.getCnt() );
      out.write("개 저장됨</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		");
 } 
      out.write("\r\n");
      out.write("		");
 } 
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- 		<div class=\"wish_content_outer\">\r\n");
      out.write("			<div class=\"wish_content1\">\r\n");
      out.write("				<img src=\"https://a0.muscache.com/im/pictures/032392ef-892e-4e85-bad1-2881905f67f0.jpg?im_w=1200\"/>\r\n");
      out.write("				<span class=\"wish_sp1\">경기도 안양시</span><br>\r\n");
      out.write("				<span class=\"wish_sp2\">0개 저장됨</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"wish_content_outer\">\r\n");
      out.write("			<div class=\"wish_content1\">\r\n");
      out.write("				<img src=\"https://a0.muscache.com/im/pictures/032392ef-892e-4e85-bad1-2881905f67f0.jpg?im_w=1200\"/>\r\n");
      out.write("				<span class=\"wish_sp1\">경기도 안양시</span><br>\r\n");
      out.write("				<span class=\"wish_sp2\">0개 저장됨</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	 	<div class=\"wish_content_outer\">\r\n");
      out.write("			<div class=\"wish_content1\">\r\n");
      out.write("				<img src=\"images/wish.png\"/>\r\n");
      out.write("				<span class=\"wish_sp1\">경기도 안양시</span><br>\r\n");
      out.write("				<span class=\"wish_sp2\">0개 저장됨</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	-->\r\n");
      out.write("		\r\n");
      out.write("	</div> <!-- inner1끝 -->\r\n");
      out.write("	<div class=\"wish_inner2\">\r\n");
      out.write("		<div class=\"wish_content2\">새로운 위시리스트 만들기</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 위시팝업 끝 -->\r\n");
      out.write("<!-- 위시 카테고리 만들기 -->\r\n");
      out.write("<div id=\"make_wish_back\"></div>\r\n");
      out.write("<div id=\"make_wish\">\r\n");
      out.write("	<div class=\"make_wish_header\">\r\n");
      out.write("		<button>\r\n");
      out.write("			<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;position:absolute;top: 20px;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg>\r\n");
      out.write("		</button>\r\n");
      out.write("		<span>위시리스트 만들기</span>\r\n");
      out.write("	</div>\r\n");
      out.write("	<form action=\"\" method=\"get\">\r\n");
      out.write("		<div class=\"make_wish_section\">\r\n");
      out.write("				<input type=\"text\" maxlength='7' name=\"wishlist_name\" placeholder=\"제목입력\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"make_wish_footer\">\r\n");
      out.write("			<input type=\"reset\" name=\"wish_reset\" class=\"wish_reset\" value=\"지우기\"/>\r\n");
      out.write("			<input name=\"wish_insert\" type=\"submit\" class=\"wish_insert\" value=\"새로 만들기\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 위시 카테고리 만들기끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--필터팝업  -->\r\n");
      out.write("<div id=\"filter_outer\" style=\"display:hidden;\"></div>\r\n");
      out.write("<div id=\"filter\" style=\"display:hidden;\">\r\n");
      out.write("	<div class=\"filter_header\">\r\n");
      out.write("		<button><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\" aria-hidden=\"true\" role=\"presentation\" focusable=\"false\" style=\"display: block; fill: none; height: 16px; width: 16px; stroke: currentcolor; stroke-width: 3; overflow: visible;\"><path d=\"m6 6 20 20M26 6 6 26\"></path></svg></button>\r\n");
      out.write("		필터\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"filter_content\">\r\n");
      out.write("		<div class=\"filter_content1\">\r\n");
      out.write("			<h1>숙소유형</h1>\r\n");
      out.write("			<span>방, 집 전체 등 원하는 숙소 유형을 검색해보세요.</span>\r\n");
      out.write("			<div class=\"fil_btns\">\r\n");
      out.write("				<button >모든유형</button>\r\n");
      out.write("				<button >방</button>\r\n");
      out.write("				<button >집 전체</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<form action=\"lmyController\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"command\" value=\"filter_room\"/>\r\n");
      out.write("			<input type=\"hidden\" name=\"category_idx\" value=\"");
      out.print(paramCate);
      out.write("\"/>\r\n");
      out.write("			<div class=\"filter_content2\">\r\n");
      out.write("				<h1>가격범위</h1>\r\n");
      out.write("				<span>1박 요금(수수료 및 세금 포함)</span>\r\n");
      out.write("				<div class=\"filter_content2-2\">\r\n");
      out.write("					<div class=\"filter_price\">\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"filter_price_input\">\r\n");
      out.write("							<span class=\"filter_span\">최저</span><br>\r\n");
      out.write("							<span class=\"filter_span2\">R</span>\r\n");
      out.write("							<input type=\"text\" id=\"fist_price\" name=\"min_price\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<span></span>\r\n");
      out.write("						<div class=\"filter_price_input\">\r\n");
      out.write("							<span class=\"filter_span\">최고</span><br>\r\n");
      out.write("							<span class=\"filter_span2\">R</span>\r\n");
      out.write("							<input type=\"text\" id=\"fist_price\" name=\"max_price\">\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<script>\r\n");
      out.write("			\r\n");
      out.write("			</script>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"filter_content3\">\r\n");
      out.write("				<input type=\"hidden\" name=\"fil3_btns\" value=\"0\"/>\r\n");
      out.write("				<input type=\"hidden\" name=\"fil3_btns2\" value=\"0\"/>\r\n");
      out.write("				<input type=\"hidden\" name=\"fil3_btns3\" value=\"0\"/>\r\n");
      out.write("				<h1>침실과 침대</h1>\r\n");
      out.write("				<span>침실</span>\r\n");
      out.write("				<div class=\"fil3_btns\">\r\n");
      out.write("					<button type=\"button\">상관없음</button>\r\n");
      out.write("					<button type=\"button\">1</button>\r\n");
      out.write("					<button type=\"button\">2</button>\r\n");
      out.write("					<button type=\"button\">3</button>\r\n");
      out.write("					<button type=\"button\">4</button>\r\n");
      out.write("					<button type=\"button\">5</button>\r\n");
      out.write("					<button type=\"button\">6</button>\r\n");
      out.write("					<button type=\"button\">7</button>\r\n");
      out.write("					<button type=\"button\">8+</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<span>침대</span>\r\n");
      out.write("				<div class=\"fil3_btns2\">\r\n");
      out.write("					<button type=\"button\">상관없음</button>\r\n");
      out.write("					<button type=\"button\">1</button>\r\n");
      out.write("					<button type=\"button\">2</button>\r\n");
      out.write("					<button type=\"button\">3</button>\r\n");
      out.write("					<button type=\"button\">4</button>\r\n");
      out.write("					<button type=\"button\">5</button>\r\n");
      out.write("					<button type=\"button\">6</button>\r\n");
      out.write("					<button type=\"button\">7</button>\r\n");
      out.write("					<button type=\"button\">8+</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("					\r\n");
      out.write("				<span>욕실</span>\r\n");
      out.write("				<div class=\"fil3_btns3\">\r\n");
      out.write("					<button type=\"button\">상관없음</button>\r\n");
      out.write("					<button type=\"button\">1</button>\r\n");
      out.write("					<button type=\"button\">2</button>\r\n");
      out.write("					<button type=\"button\">3</button>\r\n");
      out.write("					<button type=\"button\">4</button>\r\n");
      out.write("					<button type=\"button\">5</button>\r\n");
      out.write("					<button type=\"button\">6</button>\r\n");
      out.write("					<button type=\"button\">7</button>\r\n");
      out.write("					<button type=\"button\">8+</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	<div class=\"filter_footer\">\r\n");
      out.write("		<!-- <div class=\"filter_footer1\"><span>전체 해제</span></div> -->\r\n");
      out.write("		<!-- <div>숙소 n개 보기</div> -->\r\n");
      out.write("		<input type=\"reset\" value=\"전체 해제\" id=\"reset\"/>\r\n");
      out.write("		<input type=\"submit\" value=\"속소 보기\" id=\"Show_all_lists\"/>\r\n");
      out.write("	</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 필터팝업 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 슾파이더 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			//슬릭\r\n");
      out.write("			$('#cate').slick({\r\n");
      out.write("				slidesToShow: 17,\r\n");
      out.write("			    slidesToScroll: 17\r\n");
      out.write("			    \r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//카테고리 인덱스mainservlet으로 넘겨주기\r\n");
      out.write("			$(\"#cate .w\").click(function() {\r\n");
      out.write("				let selectedCate = $(this).find(\"span\").find(\"div:nth-child(3)\").text();\r\n");
      out.write("				location.href=\"lmyController?command=main2&cate=\" + selectedCate;\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("	         let cate = ");
      out.print(paramCate);
      out.write(";\r\n");
      out.write("	         $(\".w > span > div:nth-child(3)\").each(function(idx, item) {\r\n");
      out.write("	            //console.log($(item).text());\r\n");
      out.write("	            if($(item).text() == cate) {\r\n");
      out.write("	               $(item).parents(\".w\").removeClass(\"hover\").addClass(\"on\");\r\n");
      out.write("	            }\r\n");
      out.write("	         });\r\n");
      out.write("	         \r\n");
      out.write("	         // 숙소idx 파라미터 넘기기\r\n");
      out.write("	    	$(\"#content>a\").click(function(){\r\n");
      out.write("	    		let roomIdx = $(this).find(\".room_idx\").text();\r\n");
      out.write("	    		location.href=\"lmyController?command=main3&roomIdx=\" + roomIdx;\r\n");
      out.write("	    	 });\r\n");
      out.write("	         \r\n");
      out.write("	         \r\n");
      out.write("	         // 필터 ajax\r\n");
      out.write("	         //필터에있는것들 form으로 통째로 다 감싸주기\r\n");
      out.write("/* 	         $(\".filter_footer>div:nth-child(2)\").click(function(){\r\n");
      out.write("	        	 var formData = $(\"#form1\").serialize(); //form안에있는 정보 정렬햊\r\n");
      out.write("\r\n");
      out.write("	             $.ajax({\r\n");
      out.write("	                 cache : false,\r\n");
      out.write("	                 url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/testForm1\", // 요기에\r\n");
      out.write("	                 type : 'POST', \r\n");
      out.write("	                 data : formData, \r\n");
      out.write("	                 success : function(data) {\r\n");
      out.write("	                     var jsonObj = JSON.parse(data);\r\n");
      out.write("	                 }, // success \r\n");
      out.write("	         \r\n");
      out.write("	                 error : function(xhr, status) {\r\n");
      out.write("	                     alert(xhr + \" : \" + status);\r\n");
      out.write("	                 }\r\n");
      out.write("	             }); // $.ajax */\r\n");
      out.write("	    \r\n");
      out.write("	         \r\n");
      out.write("	         \r\n");
      out.write("	         \r\n");
      out.write("		});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
